---
apiVersion: batch/v1
kind: Job
metadata:
  name: curl-clusterip-job
spec:
  template:
    spec:
      containers:
      - name: curl-clusterip-job
        image: curlimages/curl:7.87.0
        command: ['sh', '-c', 'curl http://10.100.232.72:80/']
      restartPolicy: Never
  backoffLimit: 3